[build]
rustflags = []

[target.aarch64-unknown-linux-musl]
# Use Rust's built-in LLD linker
linker = "rust-lld"
rustflags = ["-C", "target-cpu=generic"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-cpu=generic"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=generic"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=generic"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=generic"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=generic"]

[env]
RUST_LOG = "info"